%% Define Initial Parameters and Useful Numbers
v_inf_earth_cycler_1 = 5.26941176470588;  %km/s (average v_inf of cycler earth flyby)
v_inf_earth_cycler_2 = 4.94647058823529;  %km/s (average v_inf of cycler earth flyby)
v_inf_earth_cycler_3 = 5.16941176470588;  %km/s (average v_inf of cycler earth flyby)
v_inf_earth_cycler_4 = 5.03235294117647;  %km/s (average v_inf of cycler earth flyby)
mu_earth = 398600.4415; %km^3/s^2 (gravitational parameter of Earth)
mu_sun = 132712440017.99;   %km^3/s^2 (gravitational parameter of Sun)
r_earth = 6378.136; %km (mean equatorial radius of Earth)
h_LEO = 500;    %km (altitude of LEO)
r_LEO = r_earth + h_LEO;
a_earth = 149597870.7;  %km (semi-major axis of Earth orbit)
a_mars = 227943822.428; %km (semi-major axis of Mars orbit)
earth_mars_TOF_1_months = 6.42429551759381;    %months (Time of Flight from Earth to Mars)
earth_mars_TOF_2_months = 6.56300189808731;    %months (Time of Flight from Earth to Mars)
earth_mars_TOF_1 = earth_mars_TOF_1_months * 30 * 24 * 3600;   %seconds
earth_mars_TOF_2 = earth_mars_TOF_2_months * 30 * 24 * 3600;   %seconds
a_Luna = 384400;    %km (radius of Lunar orbit around Earth assuming circular orbit)
a_max = 8*a_Luna;   %km (maximum semi-major axis used for transfer to Luna)
g = 9.81;   %m/s^2 (gravitational acceleration on Earth's surface)
rho_tether = 2700; %kg/m^3 (volumetric density of tether (aluminum))
d_tether = 1.2*10^(-3); %m (diameter of tether suggested in Mueterthies paper)
sigma_yield_al = 297*10^6;  %Pa (yield stress of Al 6061 according to NIST)
m_taxi = 63580; %kg (estimate from human factors of mass of taxi)


%% Compute Useful Values
v_LEO = (mu_earth/r_LEO)^.5;    %km/s (orbital velocity of circular LEO)

%% Compute Delta V for Direct to Cycler
v_p_hyp_1 = (v_inf_earth_cycler_1^2 + 2*mu_earth / r_LEO)^.5;   %km/s (periapsis velocity of earth centered hyperbola to cycler 1)
v_p_hyp_2 = (v_inf_earth_cycler_2^2 + 2*mu_earth / r_LEO)^.5;   %km/s (periapsis velocity of earth centered hyperbola to cycler 2)
v_p_hyp_3 = (v_inf_earth_cycler_3^2 + 2*mu_earth / r_LEO)^.5;   %km/s (periapsis velocity of earth centered hyperbola to cycler 3)
v_p_hyp_4 = (v_inf_earth_cycler_4^2 + 2*mu_earth / r_LEO)^.5;   %km/s (periapsis velocity of earth centered hyperbola to cycler 4)
dv_cycler_1 = v_p_hyp_1 - v_LEO;    %km/s (delta V required to reach cycler 1)
dv_cycler_2 = v_p_hyp_2 - v_LEO;    %km/s (delta V required to reach cycler 2)
dv_cycler_3 = v_p_hyp_3 - v_LEO;    %km/s (delta V required to reach cycler 3)
dv_cycler_4 = v_p_hyp_4 - v_LEO;    %km/s (delta V required to reach cycler 4)

%% Compute Delta V for Direct to Luna
a_hoh = .5*(r_LEO + a_Luna);    %km (semi-major axis of hohman transfer, which is the smallest possible transfer semi-major axis)
a_to_Luna = linspace(a_hoh, a_max, 10000); %km (range of semi-major axes for transfer orbit)
ecc_anomaly_Luna = acos((a_to_Luna - a_Luna)./(a_to_Luna - r_LEO));  % rad (eccentric anomaly of elliptical orbit to Luna at Lunar arrival)
TOF_Luna = (ecc_anomaly_Luna - (1 - r_LEO./a_to_Luna).*sin(ecc_anomaly_Luna))./(mu_earth./a_to_Luna.^3).^.5;  %seconds (Time of Flight from LEO to Luna)
dv_Luna = (2*mu_earth/r_LEO - mu_earth./a_to_Luna).^.5 - v_LEO;   %km/s (delta V required to reach Luna at a given semi-major axis)
figure(1)
plot(a_to_Luna, TOF_Luna./(3600*24))
xlabel('Semi-Major Axis of Transfer Orbit (km)')
ylabel('Time of Flight (days)')
title('Time of Flight for Transfer to Luna')

figure(2)
plot(a_to_Luna, dv_Luna)
xlabel('Semi-Major Axis of Transfer Orbit (km)')
ylabel('Delta V (km/s)')
title('Delta V for Transfer to Luna')

%% Compute Tether Length
%Note: we are assuming that the human body can sustain 6 g's for an
%unspecified amount of time.
L_tether_cycler_1 = 2*((dv_cycler_1)^2)/(6*g/1000);  %km (minimum tether length from CM that will provide an acceleration sustainable by humans)
L_tether_cycler_2 = 2*((dv_cycler_2)^2)/(6*g/1000);  %km (minimum tether length from CM that will provide an acceleration sustainable by humans)
L_tether_cycler_3 = 2*((dv_cycler_3)^2)/(6*g/1000);  %km (minimum tether length from CM that will provide an acceleration sustainable by humans)
L_tether_cycler_4 = 2*((dv_cycler_4)^2)/(6*g/1000);  %km (minimum tether length from CM that will provide an acceleration sustainable by humans)
L_tether_Luna = 2*((dv_Luna).^2)/(6*g/1000);   %km (minimum tether length from CM that will provide an acceleration sustainable by humans)
figure(3)
plot(a_to_Luna, L_tether_Luna)
xlabel('Semi-Major Axis of Transfer Orbit (km)')
ylabel('Tether Length (km)')
title('Tether Length for Transfer to Luna')

%% Compute Minimum Tether Diameter Based on Yield Stress
accel_centripetal_cycler_1 = 1000*(dv_cycler_1^2)/(L_tether_cycler_1/2); %m/s^2 (centripetal acceleration on taxi for cycler 1. note: should be equal to 6 gs)
accel_centripetal_cycler_2 = 1000*(dv_cycler_2^2)/(L_tether_cycler_2/2); %m/s^2 (centripetal acceleration on taxi for cycler 2. note: should be equal to 6 gs)
accel_centripetal_cycler_3 = 1000*(dv_cycler_3^2)/(L_tether_cycler_3/2); %m/s^2 (centripetal acceleration on taxi for cycler 3. note: should be equal to 6 gs)
accel_centripetal_cycler_4 = 1000*(dv_cycler_4^2)/(L_tether_cycler_4/2); %m/s^2 (centripetal acceleration on taxi for cycler 4. note: should be equal to 6 gs)
accel_centripetal_Luna = 1000*(dv_Luna.^2)./(L_tether_Luna./2);    %m/s^2 (centripetal acceleration on taxi for transfer to Luna. note: should be equal to 6 gs)
f_centripetal_cycler_1 = m_taxi*accel_centripetal_cycler_1; %N (centripetal force on taxi for cycler 1)
f_centripetal_cycler_2 = m_taxi*accel_centripetal_cycler_2; %N (centripetal force on taxi for cycler 2)
f_centripetal_cycler_3 = m_taxi*accel_centripetal_cycler_3; %N (centripetal force on taxi for cycler 3)
f_centripetal_cycler_4 = m_taxi*accel_centripetal_cycler_4; %N (centripetal force on taxi for cycler 4)
f_centripetal_Luna = m_taxi*accel_centripetal_Luna; %N (centripetal force on taxi for transfer to Luna)
d_tether_cycler_1 = (16*f_centripetal_cycler_1/(sigma_yield_al*pi))^.5;    %m (minimum tether diameter for cycler 1 assuming a safety factor of 4 on the yield stress)
d_tether_cycler_2 = (16*f_centripetal_cycler_2/(sigma_yield_al*pi))^.5;    %m (minimum tether diameter for cycler 2 assuming a safety factor of 4 on the yield stress)
d_tether_cycler_3 = (16*f_centripetal_cycler_3/(sigma_yield_al*pi))^.5;    %m (minimum tether diameter for cycler 3 assuming a safety factor of 4 on the yield stress)
d_tether_cycler_4 = (16*f_centripetal_cycler_4/(sigma_yield_al*pi))^.5;    %m (minimum tether diameter for cycler 4 assuming a safety factor of 4 on the yield stress)
d_tether_Luna = (16*f_centripetal_Luna./(sigma_yield_al*pi)).^.5;    %m (minimum tether diameter for transfer to Luna assuming a safety factor of 4 on the yield stress)
figure(4)
plot(a_to_Luna, d_tether_Luna)
xlabel('Semi-Major Axis of Transfer Orbit (km)')
ylabel('Tether Diameter (m)')
title('Tether Diameter for Transfer to Luna')

%% Compute Tether Mass Based on Diameter
tether_area_cycler_1 = pi*(d_tether_cycler_1/2)^2;  %m^2 (cross sectional area of tether for cycler 1)
tether_area_cycler_2 = pi*(d_tether_cycler_2/2)^2;  %m^2 (cross sectional area of tether for cycler 2)
tether_area_cycler_3 = pi*(d_tether_cycler_3/2)^2;  %m^2 (cross sectional area of tether for cycler 3)
tether_area_cycler_4 = pi*(d_tether_cycler_4/2)^2;  %m^2 (cross sectional area of tether for cycler 4)
tether_area_Luna = pi*(d_tether_Luna./2).^2;    %m^2 (cross sectional area of tether for transfer to Luna)
tether_volume_cycler_1 = tether_area_cycler_1*L_tether_cycler_1*1000;    %m^3 (volume of tether for cycler 1)
tether_volume_cycler_2 = tether_area_cycler_2*L_tether_cycler_2*1000;    %m^3 (volume of tether for cycler 2)
tether_volume_cycler_3 = tether_area_cycler_3*L_tether_cycler_3*1000;    %m^3 (volume of tether for cycler 3)
tether_volume_cycler_4 = tether_area_cycler_4*L_tether_cycler_4*1000;    %m^3 (volume of tether for cycler 4)
tether_volume_Luna = tether_area_Luna.*L_tether_Luna*1000;   %m^3 (volume of tether for transfer to Luna)
tether_mass_cycler_1 = tether_volume_cycler_1*rho_tether;   %kg (mass of tether for cycler 1)
tether_mass_cycler_2 = tether_volume_cycler_2*rho_tether;   %kg (mass of tether for cycler 2)
tether_mass_cycler_3 = tether_volume_cycler_3*rho_tether;   %kg (mass of tether for cycler 3)
tether_mass_cycler_4 = tether_volume_cycler_4*rho_tether;   %kg (mass of tether for cycler 4)
tether_mass_Luna = tether_volume_Luna*rho_tether;   %kg (mass of tether for transfer to Luna)
figure(5)
plot(a_to_Luna, tether_mass_Luna)
xlabel('Semi-Major Axis of Transfer Orbit (km)')
ylabel('Tether Mass (kg)')
title('Tether Mass for Transfer to Luna')

figure(6)
plot(TOF_Luna/(3600*24), tether_mass_Luna)
xlabel('TOF to Luna (days)')
ylabel('Tether Mass (kg)')
title('Trade-off of Mass and TOF')

figure(7)
plot(TOF_Luna/(3600*24), L_tether_Luna)
xlabel('TOF to Luna (days)')
ylabel('Tether Length (km)')
title('Trade-off of Length and TOF')